# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: nexmo-sample.dev
  secret_key_base: 945044077f02fb3866318f48dc1accfa4efbd63b170503f083416ffa4742c58711afc65ef93778b25578aecce958475401782fa9aaf9da3cb0ebe58392807a0c

test:
  domain_name: nexmo-sample.dev
  secret_key_base: 18e8247ec95d81efe9bb2278be51e852432240055f228c7719ff75b4a892186c38eaf000a6c61d8674fe965dd7779798c05c3a2814b04aa5b6e47ee945d31f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
